'use strict';
const LS_CONFIG='crm_loreny_supabase_config_v1',LS_CACHE='crm_loreny_cache_v1';
const STATUS=['Novo lead','Contato feito','Entendeu necessidade','Enviou opções','Agendou visita','Visitou imóvel','Proposta feita','Fechado','Perdido','Nutrição futura'];
const COLORS={'Novo lead':'#38bdf8','Contato feito':'#94a3b8','Entendeu necessidade':'#06b6d4','Enviou opções':'#f59e0b','Agendou visita':'#a855f7','Visitou imóvel':'#8b5cf6','Proposta feita':'#f97316','Fechado':'#22c55e','Perdido':'#ef4444','Nutrição futura':'#a16207'};
const ORIGINS=['Instagram','WhatsApp','Indicação','OLX','Placa','Site','Facebook','Outro'];
const TYPES=['Casa','Apartamento','Lote','Chácara','Comercial','Aluguel','Outro'];
const DEFAULT_TEMPLATES=[{title:'Apresentação',description:'Primeiro contato',text_content:'Olá, {nome}! Aqui é a Loreny, tudo bem? Vi seu interesse em {tipo} na região de {regiao}. Posso te ajudar com algumas opções dentro do que você procura?'},{title:'Follow-up',description:'Cobrar retorno',text_content:'Oi, {nome}! Passando para saber se conseguiu olhar as opções de {tipo} que te enviei. Alguma delas fez sentido para você?'},{title:'Novas opções',description:'Avisar oportunidade',text_content:'Oi, {nome}! Entraram novas opções de {tipo} na faixa de {valor}, na região de {regiao}. Quer que eu te envie as fotos e condições?'},{title:'Confirmar visita',description:'Agendamento',text_content:'Olá, {nome}! Confirmando nossa visita ao imóvel na região de {regiao}. Qual horário fica melhor para você?'}];
let sb=null,user=null,realtime=null,leads=[],templates=[],view='list',selectedTemplate=null,editingTemplate=null,dragging=null;
let filters={search:'',status:'',origin:'',type:'',today:false,noAction:false,quick:'all'};
const $=id=>document.getElementById(id);
document.addEventListener('DOMContentLoaded',init);
async function init(){hydrate();loadCache();initCloud();await refreshUser();events();await loadRemote();render();registerSW()}
function hydrate(){fill($('statusFilter'),STATUS,'Todos os status');fill($('originFilter'),ORIGINS,'Todas as origens');fill($('typeFilter'),TYPES,'Todos os tipos');fill($('leadStatus'),STATUS,'Selecione');fill($('leadOrigin'),ORIGINS,'Selecione');fill($('leadType'),TYPES,'Selecione')}
function fill(el,arr,label){el.innerHTML=`<option value="">${esc(label)}</option>`+arr.map(x=>`<option>${esc(x)}</option>`).join('')}
function events(){
 $('newLeadBtn').onclick=openNew;$('navNew').onclick=openNew;$('saveLeadBtn').onclick=saveLead;$('leadForm').onsubmit=e=>{e.preventDefault();saveLead()};
 $('cloudBtn').onclick=openCloud;$('saveCloudBtn').onclick=saveCloud;$('disconnectBtn').onclick=disconnectCloud;
 $('accountBtn').onclick=openAccount;$('signinBtn').onclick=signin;$('signupBtn').onclick=signup;$('signoutBtn').onclick=signout;
 $('exportBtn').onclick=exportCSV;$('importBtn').onclick=()=>$('csvInput').click();$('csvInput').onchange=e=>importCSV(e.target.files[0]);
 $('search').oninput=debounce(e=>{filters.search=e.target.value;render()},180);$('statusFilter').onchange=e=>{filters.status=e.target.value;render()};$('originFilter').onchange=e=>{filters.origin=e.target.value;render()};$('typeFilter').onchange=e=>{filters.type=e.target.value;render()};
 $('todayChip').onclick=()=>{filters.today=!filters.today;filters.noAction=false;filters.quick=filters.today?'today':'all';render()};$('noActionChip').onclick=()=>{filters.noAction=!filters.noAction;filters.today=false;filters.quick=filters.noAction?'noAction':'all';render()};$('clearFiltersBtn').onclick=clearFilters;
 document.querySelectorAll('.stat').forEach(b=>b.onclick=()=>quick(b.dataset.filter));$('listViewBtn').onclick=()=>switchView('list');$('kanbanViewBtn').onclick=()=>switchView('kanban');$('navKanban').onclick=()=>switchView(view==='kanban'?'list':'kanban');$('navToday').onclick=()=>quick('today');$('navAlerts').onclick=openAlerts;
 $('addHistBtn').onclick=addHistory;$('copyWaBtn').onclick=copyWA;$('sendWaBtn').onclick=sendWA;$('saveTplBtn').onclick=saveTemplate;$('clearTplBtn').onclick=clearTpl;
 document.querySelector('.vars').onclick=e=>{let b=e.target.closest('[data-var]');if(b)insertAt($('tplText'),b.dataset.var)};
 document.body.addEventListener('click',globalClick);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
}
function globalClick(e){let x;if(x=e.target.closest('[data-edit]'))openEdit(x.dataset.edit);else if(x=e.target.closest('[data-delete]'))delLead(x.dataset.delete);else if(x=e.target.closest('[data-hist]'))openHist(x.dataset.hist);else if(x=e.target.closest('[data-wa]'))openWA(x.dataset.wa,false);else if(x=e.target.closest('[data-twa]'))openWA(x.dataset.twa,true);else if(x=e.target.closest('[data-tpl]'))selectTpl(x.dataset.tpl);else if(x=e.target.closest('[data-edit-tpl]'))editTpl(x.dataset.editTpl);else if(x=e.target.closest('[data-del-tpl]'))delTpl(x.dataset.delTpl);else if(x=e.target.closest('[data-alert]')){ $('alertsDialog').close();openEdit(x.dataset.alert)}}
function uid(){return crypto?.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function today(){let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function fmt(d){if(!d)return'—';let [y,m,dd]=d.split('-');return`${dd}/${m}/${y}`}
function dt(x){return x?new Date(x).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):''}
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function phone(v){return String(v||'').replace(/\D/g,'')}
function waUrl(p,t=''){let d=phone(p);if(!d)return'';let full=d.startsWith('55')?d:'55'+d;return`https://wa.me/${full}${t?'?text='+encodeURIComponent(t):''}`}
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
function localTemplates(){return DEFAULT_TEMPLATES.map(t=>({id:uid(),user_id:user?.id||null,criado_em:new Date().toISOString(),...t}))}
function loadCache(){try{let d=JSON.parse(localStorage.getItem(LS_CACHE)||'{}');leads=d.leads||[];templates=d.templates||localTemplates()}catch{leads=[];templates=localTemplates()}}
function saveCache(){localStorage.setItem(LS_CACHE,JSON.stringify({leads,templates}))}
function cleanUrl(u){return(u||'').trim().replace(/\/rest\/v1\/?$/,'').replace(/\/+$/,'')}
function initCloud(){try{let c=JSON.parse(localStorage.getItem(LS_CONFIG)||'{}');if(c.url&&c.key&&window.supabase)sb=window.supabase.createClient(cleanUrl(c.url),c.key)}catch{sb=null}statusUI()}
async function refreshUser(){if(!sb){user=null;statusUI();return}let r=await sb.auth.getUser();user=r.data?.user||null;sb.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;statusUI();await loadRemote();setupRealtime();render()});statusUI();setupRealtime()}
function statusUI(){let s=$('onlineStatus'),a=$('accountBtn'),c=$('cloudStatus');if(!sb){s.textContent='Modo local';a.textContent='🔐 Login';if(c)c.textContent='Status: modo local'}else if(user){s.textContent='Online · '+user.email;a.textContent='👤 Conta';if(c)c.textContent='Status: Supabase conectado'}else{s.textContent='Nuvem configurada · faça login';a.textContent='🔐 Login';if(c)c.textContent='Status: aguardando login'}}
async function loadRemote(){if(!sb||!user){if(!templates.length)templates=localTemplates();return}try{let [l,t]=await Promise.all([sb.from('leads').select('*').order('criado_em',{ascending:false}),sb.from('wa_templates').select('*').order('criado_em',{ascending:true})]);if(l.error)throw l.error;if(t.error)throw t.error;leads=(l.data||[]).map(dbLead);templates=(t.data||[]).map(dbTpl);if(!templates.length){templates=localTemplates();await Promise.all(templates.map(saveTplRemote))}saveCache()}catch(e){console.error(e);toast('Erro ao carregar nuvem. Usando cache.','error')}}
function setupRealtime(){if(!sb||!user)return;if(realtime)sb.removeChannel(realtime);realtime=sb.channel('crm-realtime').on('postgres_changes',{event:'*',schema:'public',table:'leads'},async()=>{await loadRemote();render()}).on('postgres_changes',{event:'*',schema:'public',table:'wa_templates'},async()=>{await loadRemote();render()}).subscribe()}
function dbLead(r){return{id:r.id,user_id:r.user_id,nome:r.nome,whatsapp:r.whatsapp||'',origem:r.origem||'',tipo:r.tipo||'',regiao:r.regiao||'',valor:r.valor||'',status:r.status||'Novo lead',proxima_acao:r.proxima_acao||'',data_retorno:r.data_retorno||'',observacoes:r.observacoes||'',historico:Array.isArray(r.historico)?r.historico:[],criado_em:r.criado_em,atualizado_em:r.atualizado_em}}
function toDb(l){return{id:l.id,user_id:user?.id,nome:l.nome,whatsapp:l.whatsapp||'',origem:l.origem||'',tipo:l.tipo||'',regiao:l.regiao||'',valor:l.valor||'',status:l.status||'Novo lead',proxima_acao:l.proxima_acao||'',data_retorno:l.data_retorno||null,observacoes:l.observacoes||'',historico:l.historico||[],criado_em:l.criado_em||new Date().toISOString(),atualizado_em:new Date().toISOString()}}
function dbTpl(r){return{id:r.id,user_id:r.user_id,title:r.title,description:r.description||'',text_content:r.text_content||'',criado_em:r.criado_em}}
function toDbTpl(t){return{id:t.id,user_id:user?.id,title:t.title,description:t.description||'',text_content:t.text_content||'',criado_em:t.criado_em||new Date().toISOString(),atualizado_em:new Date().toISOString()}}
function filtered(){let q=filters.search.toLowerCase().trim(),td=today();return leads.filter(l=>{if(q&&!Object.values(l).join(' ').toLowerCase().includes(q))return false;if(filters.status&&l.status!==filters.status)return false;if(filters.origin&&l.origem!==filters.origin)return false;if(filters.type&&l.tipo!==filters.type)return false;if(filters.today&&l.data_retorno!==td)return false;if(filters.noAction&&(l.proxima_acao||'').trim())return false;if(filters.quick==='late'&&!(l.data_retorno&&l.data_retorno<td&&!['Fechado','Perdido'].includes(l.status)))return false;if(filters.quick==='visit'&&l.status!=='Agendou visita')return false;if(filters.quick==='proposal'&&l.status!=='Proposta feita')return false;if(filters.quick==='closed'&&l.status!=='Fechado')return false;return true})}
function render(){stats();filterState();renderList();if(view==='kanban')renderKanban();renderTemplates();statusUI();saveCache()}
function stats(){let td=today();$('stTotal').textContent=leads.length;$('stToday').textContent=leads.filter(l=>l.data_retorno===td&&!['Fechado','Perdido'].includes(l.status)).length;$('stLate').textContent=leads.filter(l=>l.data_retorno&&l.data_retorno<td&&!['Fechado','Perdido'].includes(l.status)).length;$('stVisit').textContent=leads.filter(l=>l.status==='Agendou visita').length;$('stProposal').textContent=leads.filter(l=>l.status==='Proposta feita').length;$('stClosed').textContent=leads.filter(l=>l.status==='Fechado').length}
function filterState(){$('todayChip').classList.toggle('active',filters.today||filters.quick==='today');$('noActionChip').classList.toggle('active',filters.noAction);$('resultCount').textContent=filtered().length}
function renderList(){let rows=filtered();$('leadList').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">Nenhum lead encontrado. Clique em <b>Novo Cliente</b>.</div>'}
function card(l){let c=COLORS[l.status]||COLORS['Novo lead'],sub=[l.origem,l.tipo,l.regiao].filter(Boolean).join(' · ')||'Sem qualificação',mark=l.data_retorno&&l.data_retorno<today()?'⚠️ ':l.data_retorno===today()?'📅 ':'';return`<article class="lead-card" style="--status-color:${c}"><div class="lead-top"><div><h3 class="lead-name">${esc(l.nome)}</h3><p class="lead-sub">${esc(sub)}</p></div><span class="badge">${esc(l.status)}</span></div><div class="lead-grid"><div class="lead-field"><span>Valor</span><strong>${esc(l.valor||'—')}</strong></div><div class="lead-field"><span>Retorno</span><strong>${mark}${fmt(l.data_retorno)}</strong></div><div class="lead-field"><span>Próxima ação</span><strong>${esc(l.proxima_acao||'—')}</strong></div><div class="lead-field"><span>WhatsApp</span><strong>${esc(l.whatsapp||'—')}</strong></div></div><div class="lead-actions"><button class="action" data-wa="${l.id}">💬</button><button class="action" data-twa="${l.id}">✨</button><button class="action" data-edit="${l.id}">✏️</button><button class="action" data-hist="${l.id}">📋</button><button class="action" data-delete="${l.id}">🗑️</button></div></article>`}
function renderKanban(){let root=$('kanban');root.innerHTML='<div class="kanban-board">'+STATUS.map(s=>{let cards=filtered().filter(l=>l.status===s),c=COLORS[s];return`<div class="kanban-col" style="--status-color:${c}"><div class="kanban-title"><span>${esc(s)}</span><span>${cards.length}</span></div><div class="kanban-body" data-status="${esc(s)}">${cards.map(kcard).join('')||'<p class="muted" style="padding:.5rem">Sem leads</p>'}</div></div>`}).join('')+'</div>';root.querySelectorAll('.kanban-card').forEach(el=>{el.ondragstart=()=>{dragging=el.dataset.id;el.style.opacity=.5};el.ondragend=()=>{dragging=null;el.style.opacity='';root.querySelectorAll('.kanban-body').forEach(b=>b.classList.remove('drag-over'))}});root.querySelectorAll('.kanban-body').forEach(col=>{col.ondragover=e=>{e.preventDefault();col.classList.add('drag-over')};col.ondragleave=()=>col.classList.remove('drag-over');col.ondrop=async e=>{e.preventDefault();col.classList.remove('drag-over');if(dragging)await moveStatus(dragging,col.dataset.status)}})}
function kcard(l){return`<article class="kanban-card" draggable="true" data-id="${l.id}"><h3>${esc(l.nome)}</h3><p>${esc([l.tipo,l.regiao].filter(Boolean).join(' · ')||'Sem detalhes')}</p><p>📅 ${fmt(l.data_retorno)}</p></article>`}
async function moveStatus(id,status){let l=leads.find(x=>x.id===id);if(!l||l.status===status)return;let old=l.status;l.status=status;l.historico=l.historico||[];l.historico.unshift({id:uid(),tipo:'Kanban',texto:`Status alterado de "${old}" para "${status}".`,criado_em:new Date().toISOString()});await persistLead(l);toast('Lead movido.','success');render()}
function switchView(v){view=v;$('leadList').classList.toggle('hidden',v!=='list');$('kanban').classList.toggle('hidden',v!=='kanban');$('listViewBtn').classList.toggle('active',v==='list');$('kanbanViewBtn').classList.toggle('active',v==='kanban');$('navKanban').classList.toggle('active',v==='kanban');render()}
function quick(k){clearFilters(false);filters.quick=k;if(k==='today')filters.today=true;if(k==='visit')filters.status='Agendou visita';if(k==='proposal')filters.status='Proposta feita';if(k==='closed')filters.status='Fechado';$('statusFilter').value=filters.status;render()}
function clearFilters(doRender=true){filters={search:'',status:'',origin:'',type:'',today:false,noAction:false,quick:'all'};$('search').value='';$('statusFilter').value='';$('originFilter').value='';$('typeFilter').value='';if(doRender)render()}
function openNew(){$('leadTitle').textContent='Novo Cliente';$('leadForm').reset();$('leadId').value='';$('leadStatus').value='Novo lead';$('leadDialog').showModal();setTimeout(()=>$('leadName').focus(),80)}
function openEdit(id){let l=leads.find(x=>x.id===id);if(!l)return;$('leadTitle').textContent='Editar Cliente';$('leadId').value=l.id;$('leadName').value=l.nome||'';$('leadWhatsapp').value=l.whatsapp||'';$('leadOrigin').value=l.origem||'';$('leadType').value=l.tipo||'';$('leadRegion').value=l.regiao||'';$('leadValue').value=l.valor||'';$('leadStatus').value=l.status||'Novo lead';$('leadReturn').value=l.data_retorno||'';$('leadAction').value=l.proxima_acao||'';$('leadNotes').value=l.observacoes||'';$('leadDialog').showModal()}
async function saveLead(){let nome=$('leadName').value.trim();if(!nome)return toast('Informe o nome.','error');let id=$('leadId').value||uid(),ex=leads.find(l=>l.id===id);let l={...(ex||{}),id,user_id:user?.id||ex?.user_id||null,nome,whatsapp:$('leadWhatsapp').value.trim(),origem:$('leadOrigin').value,tipo:$('leadType').value,regiao:$('leadRegion').value.trim(),valor:$('leadValue').value.trim(),status:$('leadStatus').value||'Novo lead',data_retorno:$('leadReturn').value||'',proxima_acao:$('leadAction').value.trim(),observacoes:$('leadNotes').value.trim(),historico:ex?.historico||[],criado_em:ex?.criado_em||new Date().toISOString()};if(ex)Object.assign(ex,l);else leads.unshift(l);await persistLead(l);$('leadDialog').close();toast(ex?'Cliente atualizado.':'Cliente criado.','success');render()}
async function persistLead(l){saveCache();if(!sb||!user)return;let r=await sb.from('leads').upsert(toDb(l));if(r.error){console.error(r.error);toast('Erro ao salvar na nuvem.','error')}}
async function delLead(id){let l=leads.find(x=>x.id===id);if(!l||!confirm(`Excluir "${l.nome}"?`))return;leads=leads.filter(x=>x.id!==id);saveCache();if(sb&&user){let r=await sb.from('leads').delete().eq('id',id);if(r.error)toast('Erro ao excluir na nuvem.','error')}toast('Cliente excluído.','info');render()}
function openHist(id){let l=leads.find(x=>x.id===id);if(!l)return;$('histLeadId').value=id;$('histLeadName').textContent=l.nome;$('histText').value='';renderHist(l);$('historyDialog').showModal()}
function renderHist(l){let h=l.historico||[];$('histList').innerHTML=h.length?h.map(i=>`<div class="history-item"><b>${esc(i.tipo||'Interação')}</b><p>${esc(i.texto||i.obs||'')}</p><small>${dt(i.criado_em||i.data)}</small></div>`).join(''):'<p class="muted">Nenhuma interação.</p>'}
async function addHistory(){let l=leads.find(x=>x.id===$('histLeadId').value),txt=$('histText').value.trim();if(!l||!txt)return toast('Descreva a interação.','error');l.historico=l.historico||[];l.historico.unshift({id:uid(),tipo:$('histKind').value,texto:txt,criado_em:new Date().toISOString()});$('histText').value='';renderHist(l);await persistLead(l);render();toast('Histórico salvo.','success')}
function openWA(id,useTpl){let l=leads.find(x=>x.id===id);if(!l)return;if(!useTpl){if(!l.whatsapp)return toast('Lead sem WhatsApp.','error');window.open(waUrl(l.whatsapp),'_blank','noopener');return}$('waLeadId').value=id;$('waLeadName').textContent=`${l.nome} · ${l.whatsapp||'sem telefone'}`;selectedTemplate=templates[0]?.id||null;renderTemplates();if(selectedTemplate)selectTpl(selectedTemplate);$('waDialog').showModal()}
function renderTemplates(){let grid=$('templateGrid');if(!grid)return;grid.innerHTML=templates.map(t=>`<button class="template-card ${t.id===selectedTemplate?'active':''}" data-tpl="${t.id}"><b>${esc(t.title)}</b><span>${esc(t.description||'Sem descrição')}</span></button>`).join('');$('tplManage').innerHTML=templates.map(t=>`<div class="tpl-item"><div><b>${esc(t.title)}</b><p class="muted">${esc(t.description||'')}</p></div><div><button class="action" data-edit-tpl="${t.id}">✏️</button><button class="action" data-del-tpl="${t.id}">🗑️</button></div></div>`).join('')}
function selectTpl(id){selectedTemplate=id;let t=templates.find(x=>x.id===id),l=leads.find(x=>x.id===$('waLeadId').value);if(!t||!l)return;$('waText').value=fillTpl(t.text_content,l);renderTemplates()}
function fillTpl(txt,l){let first=(l.nome||'Cliente').trim().split(/\s+/)[0];return(txt||'').replaceAll('{nome}',first).replaceAll('{tipo}',(l.tipo||'imóvel').toLowerCase()).replaceAll('{regiao}',l.regiao||'excelente região').replaceAll('{valor}',l.valor||'sua faixa de interesse')}
async function copyWA(){let t=$('waText').value.trim();if(!t)return toast('Mensagem vazia.','error');await navigator.clipboard.writeText(t);toast('Mensagem copiada.','success')}
async function sendWA(){let l=leads.find(x=>x.id===$('waLeadId').value),t=$('waText').value.trim();if(!l?.whatsapp)return toast('Lead sem WhatsApp.','error');if(!t)return toast('Mensagem vazia.','error');l.historico=l.historico||[];l.historico.unshift({id:uid(),tipo:'WhatsApp',texto:'Mensagem aberta: '+t.slice(0,160),criado_em:new Date().toISOString()});await persistLead(l);window.open(waUrl(l.whatsapp,t),'_blank','noopener');$('waDialog').close();render()}
function clearTpl(){editingTemplate=null;$('tplId').value='';$('tplTitle').value='';$('tplDesc').value='';$('tplText').value=''}
function editTpl(id){let t=templates.find(x=>x.id===id);if(!t)return;editingTemplate=id;$('tplId').value=id;$('tplTitle').value=t.title;$('tplDesc').value=t.description||'';$('tplText').value=t.text_content}
async function saveTemplate(){let title=$('tplTitle').value.trim(),text=$('tplText').value.trim();if(!title||!text)return toast('Preencha título e texto.','error');let id=editingTemplate||uid(),ex=templates.find(t=>t.id===id),data={...(ex||{}),id,user_id:user?.id||null,title,description:$('tplDesc').value.trim(),text_content:text,criado_em:ex?.criado_em||new Date().toISOString()};if(ex)Object.assign(ex,data);else templates.push(data);await saveTplRemote(data);clearTpl();renderTemplates();toast('Modelo salvo.','success')}
async function saveTplRemote(t){saveCache();if(!sb||!user)return;let r=await sb.from('wa_templates').upsert(toDbTpl(t));if(r.error)toast('Erro ao salvar modelo.','error')}
async function delTpl(id){let t=templates.find(x=>x.id===id);if(!t||!confirm(`Excluir modelo "${t.title}"?`))return;templates=templates.filter(x=>x.id!==id);saveCache();if(sb&&user)await sb.from('wa_templates').delete().eq('id',id);renderTemplates();toast('Modelo excluído.','info')}
function insertAt(el,v){let s=el.selectionStart||0,e=el.selectionEnd||0;el.value=el.value.slice(0,s)+v+el.value.slice(e);el.selectionStart=el.selectionEnd=s+v.length;el.focus()}
function openCloud(){try{let c=JSON.parse(localStorage.getItem(LS_CONFIG)||'{}');$('supaUrl').value=c.url||'';$('supaKey').value=c.key||''}catch{}statusUI();$('cloudDialog').showModal()}
async function saveCloud(){let url=cleanUrl($('supaUrl').value),key=$('supaKey').value.trim();if(!url||!key)return toast('Informe URL e Anon Key.','error');try{let client=window.supabase.createClient(url,key);let r=await client.from('leads').select('id').limit(1);if(r.error)throw r.error;localStorage.setItem(LS_CONFIG,JSON.stringify({url,key}));sb=client;await refreshUser();$('cloudDialog').close();toast('Supabase conectado. Faça login.','success');openAccount()}catch(e){console.error(e);toast('Falha ao conectar. Verifique SQL, URL e Anon Key.','error')}}
function disconnectCloud(){localStorage.removeItem(LS_CONFIG);sb=null;user=null;$('cloudDialog').close();statusUI();toast('Nuvem desconectada.','info')}
function openAccount(){if(!sb){toast('Configure a nuvem primeiro.','info');openCloud();return}statusUI();$('accountDialog').showModal()}
async function signin(){let email=$('email').value.trim(),password=$('password').value;if(!email||!password)return toast('Informe e-mail e senha.','error');let r=await sb.auth.signInWithPassword({email,password});if(r.error)return toast(r.error.message,'error');user=r.data.user;await loadRemote();$('accountDialog').close();render();toast('Login realizado.','success')}
async function signup(){let email=$('email').value.trim(),password=$('password').value;if(!email||!password)return toast('Informe e-mail e senha.','error');let r=await sb.auth.signUp({email,password});if(r.error)return toast(r.error.message,'error');user=r.data.user||null;toast('Acesso criado. Confira se precisa confirmar e-mail.','success');if(user){await loadRemote();$('accountDialog').close();render()}}
async function signout(){if(sb)await sb.auth.signOut();user=null;leads=[];templates=localTemplates();$('accountDialog').close();render();toast('Você saiu.','info')}
function openAlerts(){let td=today(),active=leads.filter(l=>!['Fechado','Perdido'].includes(l.status)),arr=[];active.forEach(l=>{if(l.data_retorno&&l.data_retorno<=td)arr.push({l,danger:l.data_retorno<td,title:(l.data_retorno<td?'Retorno atrasado: ':'Retorno hoje: ')+l.nome,desc:`Data: ${fmt(l.data_retorno)} · Ação: ${l.proxima_acao||'sem ação'}`});if(!(l.proxima_acao||'').trim())arr.push({l,danger:false,title:'Sem próxima ação: '+l.nome,desc:'Defina o próximo passo.'})});$('alertsList').innerHTML=arr.length?arr.map(a=>`<button class="alert-item ${a.danger?'danger':''}" data-alert="${a.l.id}"><b>${esc(a.title)}</b><p>${esc(a.desc)}</p></button>`).join(''):'<div class="empty">Tudo em dia.</div>';$('alertsDialog').showModal()}
function toast(msg,type='info'){let el=document.createElement('div');el.className='toast';el.textContent=msg;if(type==='error')el.style.borderLeftColor='#ef4444';if(type==='success')el.style.borderLeftColor='#22c55e';$('toasts').appendChild(el);setTimeout(()=>el.remove(),3600)}
function csvEsc(v){let s=String(v??'');return/[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function exportCSV(){if(!leads.length)return toast('Sem leads para exportar.');let h=['Nome','WhatsApp','Origem','Tipo','Região','Valor','Status','Próxima Ação','Data Retorno','Observações'],rows=leads.map(l=>[l.nome,l.whatsapp,l.origem,l.tipo,l.regiao,l.valor,l.status,l.proxima_acao,l.data_retorno,l.observacoes]);let csv='\uFEFF'+[h,...rows].map(r=>r.map(csvEsc).join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`crm-loreny-${today()}.csv`;a.click();URL.revokeObjectURL(url)}
function parseLine(line){let out=[],cur='',q=false;for(let i=0;i<line.length;i++){let c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out}
async function importCSV(file){if(!file)return;let text=await file.text(),lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return toast('CSV vazio.','error');let h=parseLine(lines[0]).map(x=>x.toLowerCase()),count=0;for(let line of lines.slice(1)){let cols=parseLine(line),r={};h.forEach((k,i)=>r[k]=cols[i]||'');let nome=r.nome||r['nome do cliente'];if(!nome)continue;let l={id:uid(),user_id:user?.id||null,nome,whatsapp:r.whatsapp||'',origem:r.origem||'',tipo:r.tipo||r['tipo de imóvel']||'',regiao:r.região||r.regiao||'',valor:r.valor||'',status:STATUS.includes(r.status)?r.status:'Novo lead',proxima_acao:r['próxima ação']||r.proxima_acao||'',data_retorno:r['data retorno']||r.data_retorno||'',observacoes:r.observações||r.observacoes||'',historico:[],criado_em:new Date().toISOString()};leads.unshift(l);count++;await persistLead(l)}$('csvInput').value='';render();toast(`${count} leads importados.`,'success')}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=1.0').catch(console.error)}
